#!/bin/bash
ADDR=127.0.0.1:9999
ps -ef |grep 'godoc'|grep -v 'grep'|grep "$ADDR" > /dev/null
if [ $? -ne 0 ];then
	nohup godoc -http "$ADDR" > /dev/null 2>&1  &
	echo "started godoc server!"
fi
open http://"$ADDR"
