#! /bin/bash
set -e

DOMAIN=${DOMAIN:-qubestash}

DOCKER_BINARY=docker
# DOCKER_BINARY="echo docker"

# curl -Ss https://hub.docker.com/_/jenkins/ | grep Dockerfile | grep latest | head -n 1 | awk -F '>' '{print $6}' | awk -F '<' '{print $1}'

version=${1:-2.60.1}

variants=${2:-$version ${version}-alpine}
# variants=${2:-alpine}
# variants=${2:-latest}

echo
cat <<DOCKER_STATEMENT
===============================================================================
===============================================================================
== Building wordpress Dockerfiles for 
== Varnish Cache Versions: $version
== Variants: $variants
===============================================================================
===============================================================================
DOCKER_STATEMENT
# exit 0

#
#
#
QubeStash::Wordpress::init(){
    local variant=$1
    cat <<DOCKER_FILE
#
# NOTE: THIS DOCKERFILE IS GENERATED VIA "update.sh"
#
# PLEASE DO NOT EDIT IT DIRECTLY.
#

##<autogenerated>##
FROM jenkins:$variant

MAINTAINER Dragos Cirjan <dragos.cirjan@gmail.com>

DOCKER_FILE
}

#
#
#
QubeStash::Wordpress::env(){
    cat <<DOCKER_FILE
ENV JENKINS_THEME_MATERIAL_COLOR deep-purple

ENV JENKINS_INSTALL_PLUGINS 'simple-theme-plugin'
##</autogenerated>##

DOCKER_FILE
}

#
#
#
QubeStash::Wordpress::dependencies(){
    local variant=$1
}

#
#
#
QubeStash::Wordpress::install(){
    cat <<DOCKER_FILE

##<autogenerated>##
# | Plugin              | Used For                                   |
# | simple-theme-plugin | http://afonsof.com/jenkins-material-theme/ |
# | ssh                 | Deploying over ssh                         |
RUN install-plugins.sh simple-theme-plugin ssh

DOCKER_FILE
}

#
#
#
QubeStash::Wordpress::configure(){
    cat <<DOCKER_FILE

##</autogenerated>##

DOCKER_FILE
}

#
#
#
QubeStash::Wordpress::entrypoint(){
    local variant=$1

cat <<DOCKER_FILE
##<autogenerated>##
COPY docker-entrypoint.sh /

ENTRYPOINT ["sh", "/docker-entrypoint.sh"]

EXPOSE 80
##</autogenerated>##
DOCKER_FILE
}

for variant in $variants; do

    dockerPath=${variant/-/\/}
    dockerFile="$dockerPath/Dockerfile"

    ( rm -rf $dockerPath || true ) && mkdir -p $dockerPath && cp docker-* $dockerPath
    cp -rdf docker-entrypoint.sh $dockerPath

    QubeStash::Wordpress::init $variant > $dockerFile

    QubeStash::Wordpress::env >> $dockerFile
    
    QubeStash::Wordpress::dependencies $variant >> $dockerFile

    QubeStash::Wordpress::install >> $dockerFile

    QubeStash::Wordpress::configure >> $dockerFile

    QubeStash::Wordpress::entrypoint >> $dockerFile

    mainTag="$DOMAIN/jenkins:$variant"
    
    $DOCKER_BINARY build -t $mainTag ${dockerFile/Dockerfile/}

    for targetVersion in ${version%.*} ${version}; do
        targetVariant=$variant

        localTag=$DOMAIN/jenkins:$targetVersion

        if [ $mainTag != $localTag ]; then
            $DOCKER_BINARY tag $mainTag $localTag
        fi

        if [ "$targetVersion" = "$version" ]; then

            if [ "$variant" = "$version" ]; then
                $DOCKER_BINARY tag $mainTag $DOMAIN/jenkins:latest
            fi

            if [ "$variant" = "${version}-alpine" ]; then
                $DOCKER_BINARY tag $mainTag $DOMAIN/jenkins:alpine
            fi
        fi
    done
done